version: '3.3'

services:
  wekan-db:
    image: mongo:3.2.18
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    command: mongod --smallfiles --oplogSize 128
    volumes:
      - ${LOCAL_DB_DIR}:/data/db
      - ${LOCAL_DB_DUMP_DIR}:/dump

  wekan:
    image: wekanteam/wekan:latest
    container_name: ${APP_CONTAINER_NAME}
    links:
      - ${DB_CONTAINER_NAME}
    environment:
      MONGO_URL: ${MONGO_URL}
      ROOT_URL: ${VIRTUAL_HOST}
      Accounts_UseDNSDomainCheck: "true"
#     MAIL_URL: ${MAIL_URL}
#     MAIL_FROM: ${MAIL_FROM}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - 8080:80
    restart: always

networks:
    default:
       external:
         name: ${NETWORK}
